updated install and unintall program with nvm

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,50 +17,144 @@
 
 
 
-# STEP 1 : Check for an npm installation
+# ---- INIT ----
+
+#prepare folders
+mkdir -p Angular JSONserver
+
+#presentation
 clear
-echo -e "Welcome in the VoiceWeb installation program.\n"
-echo -e "Checking for an existing version of npm installed...\n"
+echo "Welcome in the VoiceWeb installation program.\n"
+echo -e "\n[Press ENTER to continue]"
+read
 
-npm help &> /dev/null
 
-#redirect if no npm installation is found
-if [[ $? == 0 ]]; then
-    echo -e "npm installation detected !\n"
-    sleep 5
+
+
+
+
+# ---- REQUIREMENTS ----
+
+# git
+clear
+git version &> /dev/null && {
+	echo "git already installed."
+} || {
+	echo "VoiceWeb requires package 'git'."
+	echo "Please install it before retrying :"
+	echo "    > sudo apt install git"
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
+echo -e "\n[Press ENTER to continue]"
+read
+
+#npm
+clear
+npm --version &> /dev/null && {
+	echo "npm already installed."
+} || {
+	echo "VoiceWeb requires package 'npm'."
+	echo "Please install it before retrying :"
+	echo "    > sudo apt install npm"
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
+echo -e "\n[Press ENTER to continue]"
+read
+
+
+
+
+
+
+# ---- NODE.JS ----
+
+#nvm
+clear
+if [[ -e nvm ]]; then
+	echo "nvm already installed."
 else
-    echo -e "Package \"npm\" is not detected on your computer."
-    echo -e "Please install it before installing VoiceWeb :\n"
-    echo -e "    > sudo apt install npm\n"
-    exit 1
+	echo -e "Creating a local installation of nvm...\n"
+	git clone https://github.com/nvm-sh/nvm || {
+		echo "Unable to get nvm (from GitHub)."
+		echo "Maybe you do have not a correct Internet connection ?"
+		echo -e "\n[Installation cancelled]"
+		exit 1
+	}
+	echo -e "\nDone."
 fi
+echo -e "\n[Press ENTER to continue]"
+read
 
-
-
-# STEP 2 : Create a local installation of Angular
+#nodejs
 clear
-echo -e "Creating a local installation of Angular...\n"
+node --version &> /dev/null && {
+	echo "node.js already installed."
+} || {
+	echo -e "Installing node.js...\n"
+	./nvm/nvm.sh install node || {
+		echo "Unable to install node.js (using nvm)."
+		echo "Maybe you do not have a correct Internet connection ?"
+		echo -e "Trying to use './nvm.sh install node' did not work."
+		echo -e "\n[Installation cancelled]"
+		exit 1
+	}
+}
+echo -e "\n[Press ENTER to continue]"
+read
 
-mkdir Angular
+
+
+
+
+
+# ---- ANGULAR ----
+
+#angular
+clear
+if [[ -e Angular ]]
 cd Angular
-npm install @angular/cli
+echo -e "Creating a local installation of Angular...\n"
+npm install @angular/cli && {
+	echo -e "\nDone."
+} || {
+	echo "Unable to install angular (using npm)."
+	echo "Maybe you do not have a correct Internet connection ?"
+	echo -e "Trying to use 'npm install @angular/cli' did not work."
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
+echo -e "\n[Press ENTER to continue]"
+read
 
-
-
-# STEP 3 : Create a local installation of JSON server
+#JSON server
 clear
 echo -e "Creating a local installation of JSON server...\n"
-
-mkdir ../JSONserver
 cd ../JSONserver
-npm install json-server
+npm install json-server && {
+	echo -e "\nDone."
+} || {
+	echo "Unable to install json server (using npm)."
+	echo "Maybe you do not have a correct Internet connection ?"
+	echo -e "Trying to use 'npm install json-server' did not work."
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
 cd ..
+echo -e "\n[Press ENTER to continue]"
+read
 
 
 
-# STEP 4 : Create a new Angular project
+
+
+
+# ---- VOICE WEB ----
+
+#make sure user knows what to do
 ok=""
-while [[ ! $ok = "y" ]]
+while [[ ! $ok = 'y' ]]
 do
     clear
     echo -e "We will now prepare the project installation.\n"
@@ -68,27 +162,45 @@ do
     echo -e "and select \"CSS\" for default style format.\n"
 	read -p "Is that ok ? [y/n] > " ok
 done
-echo -e "\nCreating new project...\n"
 
-./Angular/node_modules/.bin/ng new VoiceWeb
-
-
-
-# STEP 5 : Take the generated libraries into folder "Project"
-mv VoiceWeb/node_modules Project/
-mv VoiceWeb/e2e Project/
-rm -rf VoiceWeb
-
-
-
-# STEP 6 : Move the "run" application up and destroy the "install"
-mv Project/run $PWD
-rm install
+#create a new Angular project
+echo -e "\nCreating new Angular project...\n"
+./Angular/node_modules/.bin/ng new VoiceWeb && {
+	echo -e "\nDone."
+} || {
+	echo "Unable to create angular project."
+	echo -e "Trying to use 'ng new VoiceWeb' did not work."
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
+echo -e "\n[Press ENTER to continue]"
+read
 
 
 
-# Finished !
+
+
+
+# ---- GATHERING ----
+
+#move the generated libraries into "Project" + move up "run" & "uninstall" + remove "install"
+echo -e "\nReorganizing files & folders...\n"
+mv VoiceWeb/node_modules Project/ && \
+mv VoiceWeb/e2e Project/          && \
+rm -rf VoiceWeb                   && \
+mv Project/run $PWD               && \
+mv Project/uninstall $PWD         && \
+rm install                        && {
+	echo -e "\nDone."
+} || {
+	echo "Unable to reorganize files correctly."
+	echo -e "\n[Installation cancelled]"
+	exit 1
+}
+echo -e "\n[Press ENTER to continue]"
+read
+
+#finished !
 clear
 echo -e "VoiceWeb installation has finished !\n"
 echo "Enjoy !                I.A. & eerrtrr"
-
